SET @YEAR_VAL = "2023-24";
SET @TITLE_VAL = "RICE CROP";
SET @CROP_TYPE_VAL = "kharif";

WITH AGG_TABLE AS (
    SELECT CROP_TYPE, YEAR, TITLE, DIVISIONS, DISTRICTS, MEASURE_TYPE, UNIT, SUM(MEASURE_VALUE) VAL
    FROM crop_data.crops 
    WHERE YEAR = @YEAR_VAL AND TITLE = @TITLE_VAL AND CROP_TYPE = @CROP_TYPE_VAL
    GROUP BY CROP_TYPE, YEAR, TITLE, DIVISIONS, DISTRICTS, MEASURE_TYPE, UNIT
)
SELECT GROUP_CONCAT(DISTINCT CONCAT('ROUND(COALESCE(SUM(CASE WHEN MEASURE_TYPE = ''', MEASURE_TYPE, ''' THEN VAL END), 0), 2) AS `', MEASURE_TYPE, '`')) INTO @CASE_STMNT FROM AGG_TABLE;

SET @CASE_STMNT = CONCAT(
    'WITH AGG_TABLE AS (
        SELECT CROP_TYPE, YEAR, TITLE, DIVISIONS, DISTRICTS, MEASURE_TYPE, UNIT, SUM(MEASURE_VALUE) VAL
        FROM crop_data.crops 
        WHERE YEAR = "', @YEAR_VAL, '" AND TITLE = "', @TITLE_VAL, '" AND CROP_TYPE = "', @CROP_TYPE_VAL, '"
        GROUP BY CROP_TYPE, YEAR, TITLE, DIVISIONS, DISTRICTS, MEASURE_TYPE, UNIT
    ) SELECT YEAR, TITLE, DIVISIONS, DISTRICTS, UNIT, ',
    @CASE_STMNT, 
    ' FROM AGG_TABLE GROUP BY YEAR, TITLE, DIVISIONS, DISTRICTS, UNIT'
);

SELECT @CASE_STMNT;

PREPARE stmt FROM @CASE_STMNT;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;